name: admin_app
description: "The admin interface of Banque Stage"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  collection: ^1.16.0
  provider: ^6.0.3
  uuid: 4.5.1
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_auth_mocks: ^0.14.1
  web_socket_client: ^0.2.0
  dart_jsonwebtoken: ^2.17.0
  go_router: ^14.2.7
  flutter_form_builder: ^10.0.1
  crcrme_material_theme:
    path: ../external/crcrme_material_theme
  enhanced_containers_foundation:
  enhanced_containers:
  common:
    path: ../common

dependency_overrides:
  enhanced_containers_foundation:
    path: ../external/enhanced_containers/plugins/enhanced_containers_foundation
  enhanced_containers:
    path: ../external/enhanced_containers/


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
