name: stagess_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none 

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^3.1.0
  logging: ^1.3.0
  mutex: ^3.1.0
  stagess_common:
    path: ../stagess_common
  mysql1: ^0.20.0
  http: ^1.4.0
  pointycastle: ^3.0.0
  firebase_admin: ^0.3.0+2

dependency_overrides:
  enhanced_containers_foundation:
    path: ../external/enhanced_containers/plugins/enhanced_containers_foundation

  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
